In [15]:
import yfinance as yf
import pandas as pd

In [ ]:
msft = yf.Ticker("MSFT")

In [2]:
msft.options

('2023-10-06',
 '2023-10-13',
 '2023-10-20',
 '2023-10-27',
 '2023-11-03',
 '2023-11-10',
 '2023-11-17',
 '2023-12-15',
 '2024-01-19',
 '2024-02-16',
 '2024-03-15',
 '2024-04-19',
 '2024-05-17',
 '2024-06-21',
 '2024-09-20',
 '2024-12-20',
 '2025-01-17',
 '2025-06-20',
 '2025-12-19',
 '2026-01-16')

In [14]:
calls = msft.option_chain(msft.options[0]).calls
puts = msft.option_chain(msft.options[0]).puts

In [16]:
df = pd.concat([calls, puts], axis=0)

In [17]:
df

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,MSFT231006C00170000,2023-10-04 16:57:57+00:00,170.0,149.60,147.05,151.05,6.450012,4.505772,19.0,35,3.320314,True,REGULAR,USD
1,MSFT231006C00215000,2023-09-28 15:23:16+00:00,215.0,97.30,102.50,106.35,0.000000,0.000000,5.0,5,2.695316,True,REGULAR,USD
2,MSFT231006C00220000,2023-09-13 17:44:37+00:00,220.0,117.65,97.05,101.35,0.000000,0.000000,NaN,4,2.318364,True,REGULAR,USD
3,MSFT231006C00225000,2023-09-29 15:56:43+00:00,225.0,93.00,92.40,96.10,0.000000,0.000000,5.0,6,2.253911,True,REGULAR,USD
4,MSFT231006C00230000,2023-09-27 17:48:09+00:00,230.0,80.70,87.60,91.10,0.000000,0.000000,1.0,0,2.226567,True,REGULAR,USD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,MSFT231006P00395000,2023-09-20 19:37:09+00:00,395.0,72.91,73.80,78.00,0.000000,0.000000,1.0,0,2.056157,True,REGULAR,USD
52,MSFT231006P00410000,2023-08-25 16:15:03+00:00,410.0,89.18,91.00,94.35,0.000000,0.000000,57.0,0,2.220219,True,REGULAR,USD
53,MSFT231006P00420000,2023-08-25 16:11:08+00:00,420.0,99.52,101.00,104.35,0.000000,0.000000,112.0,0,2.378910,True,REGULAR,USD
54,MSFT231006P00460000,2023-09-20 17:03:45+00:00,460.0,133.59,139.05,143.00,0.000000,0.000000,NaN,0,3.068362,True,REGULAR,USD
55,MSFT231006P00470000,2023-09-12 15:39:41+00:00,470.0,136.99,149.20,153.00,0.000000,0.000000,NaN,0,1.929688,True,REGULAR,USD